"""add log_archive table

Revision ID: cf5130012274
Revises: 1257491253b2
Create Date: 2026-07-28 02:54:59.955177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5130012274'
down_revision: Union[str, Sequence[str], None] = '1257491253b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_archive',
    sa.Column('log_archive_id', sa.String(length=32), nullable=False),
    sa.Column('log_type', sa.String(length=32), nullable=False),
    sa.Column('period_from', sa.DateTime(), nullable=False),
    sa.Column('period_to', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('log_archive_id')
    )
    op.create_index(op.f('ix_log_archive_created_at'), 'log_archive', ['created_at'], unique=False)
    op.create_index(op.f('ix_log_archive_log_type'), 'log_archive', ['log_type'], unique=False)
    op.create_index(op.f('ix_log_archive_period_to'), 'log_archive', ['period_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_archive_period_to'), table_name='log_archive')
    op.drop_index(op.f('ix_log_archive_log_type'), table_name='log_archive')
    op.drop_index(op.f('ix_log_archive_created_at'), table_name='log_archive')
    op.drop_table('log_archive')
    # ### end Alembic commands ###
