"""initial schema

Revision ID: eca5a1c29385
Revises: 
Create Date: 2026-07-28 01:24:34.742306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca5a1c29385'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_ip',
    sa.Column('allowed_ip_id', sa.String(length=32), nullable=False),
    sa.Column('cidr', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('applies_to', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('allowed_ip_id')
    )
    op.create_table('app_setting',
    sa.Column('setting_key', sa.String(length=128), nullable=False),
    sa.Column('setting_value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('audit_log',
    sa.Column('audit_log_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('user_display_name', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('os_info', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('audit_log_id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('change_history',
    sa.Column('change_history_id', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('changed_by', sa.String(length=32), nullable=True),
    sa.Column('changed_by_name', sa.String(length=128), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('change_history_id')
    )
    op.create_index(op.f('ix_change_history_changed_at'), 'change_history', ['changed_at'], unique=False)
    op.create_index('ix_history_target', 'change_history', ['target_type', 'target_id', 'changed_at'], unique=False)
    op.create_table('company',
    sa.Column('company_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('name_kana', sa.String(length=256), nullable=True),
    sa.Column('name_normalized', sa.String(length=256), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('tel', sa.String(length=64), nullable=True),
    sa.Column('fax', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=256), nullable=True),
    sa.Column('merged_into_company_id', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=32), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_company_name_normalized'), 'company', ['name_normalized'], unique=False)
    op.create_table('department',
    sa.Column('department_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_department_id', sa.String(length=32), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['parent_department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_table('person',
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name_kana', sa.String(length=64), nullable=True),
    sa.Column('first_name_kana', sa.String(length=64), nullable=True),
    sa.Column('full_name_normalized', sa.String(length=128), nullable=False),
    sa.Column('latest_card_id', sa.String(length=32), nullable=True),
    sa.Column('merged_into_person_id', sa.String(length=32), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=32), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['merged_into_person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_index(op.f('ix_person_full_name_normalized'), 'person', ['full_name_normalized'], unique=False)
    op.create_table('csv_export_log',
    sa.Column('csv_export_log_id', sa.String(length=32), nullable=False),
    sa.Column('audit_log_id', sa.String(length=32), nullable=False),
    sa.Column('export_scope', sa.String(length=32), nullable=False),
    sa.Column('search_condition', sa.JSON(), nullable=True),
    sa.Column('exported_columns', sa.JSON(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('control_number', sa.String(length=64), nullable=False),
    sa.Column('confirmed_large_export', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['audit_log_id'], ['audit_log.audit_log_id'], ),
    sa.PrimaryKeyConstraint('csv_export_log_id'),
    sa.UniqueConstraint('audit_log_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('login_id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('department_id', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('external_access_allowed', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.department_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('login_id')
    )
    op.create_table('business_card',
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('person_id', sa.String(length=32), nullable=False),
    sa.Column('company_id', sa.String(length=32), nullable=True),
    sa.Column('company_name_raw', sa.String(length=256), nullable=True),
    sa.Column('department_name', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('card_type', sa.String(length=32), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('exchanged_on', sa.DateTime(), nullable=True),
    sa.Column('exchanged_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_card_id', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('verified_by_user_id', sa.String(length=32), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.String(length=32), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['exchanged_by_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('card_id')
    )
    op.create_index(op.f('ix_business_card_company_id'), 'business_card', ['company_id'], unique=False)
    op.create_index(op.f('ix_business_card_deleted_at'), 'business_card', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_business_card_is_latest'), 'business_card', ['is_latest'], unique=False)
    op.create_index(op.f('ix_business_card_person_id'), 'business_card', ['person_id'], unique=False)
    op.create_index('ix_card_exchanged_on', 'business_card', ['exchanged_on'], unique=False)
    op.create_index('ix_card_person_latest', 'business_card', ['person_id', 'is_latest'], unique=False)
    op.create_table('device',
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('os_info', sa.String(length=128), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('import_job',
    sa.Column('import_job_id', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('import_job_id')
    )
    op.create_index(op.f('ix_import_job_created_at'), 'import_job', ['created_at'], unique=False)
    op.create_table('login_attempt',
    sa.Column('login_attempt_id', sa.String(length=32), nullable=False),
    sa.Column('login_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('login_attempt_id')
    )
    op.create_index(op.f('ix_login_attempt_attempted_at'), 'login_attempt', ['attempted_at'], unique=False)
    op.create_table('card_contact',
    sa.Column('card_contact_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=False),
    sa.Column('contact_type', sa.String(length=16), nullable=False),
    sa.Column('value_raw', sa.String(length=256), nullable=False),
    sa.Column('value_normalized', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['business_card.card_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_contact_id')
    )
    op.create_index(op.f('ix_card_contact_card_id'), 'card_contact', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_contact_value_normalized'), 'card_contact', ['value_normalized'], unique=False)
    op.create_table('card_image',
    sa.Column('card_image_id', sa.String(length=32), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('import_item_id', sa.String(length=32), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('variant', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('original_mime_type', sa.String(length=64), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('correction_applied', sa.JSON(), nullable=True),
    sa.Column('quality_warning', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['business_card.card_id'], ),
    sa.PrimaryKeyConstraint('card_image_id')
    )
    op.create_index(op.f('ix_card_image_card_id'), 'card_image', ['card_id'], unique=False)
    op.create_index(op.f('ix_card_image_checksum'), 'card_image', ['checksum'], unique=False)
    op.create_index(op.f('ix_card_image_import_item_id'), 'card_image', ['import_item_id'], unique=False)
    op.create_table('import_file',
    sa.Column('import_file_id', sa.String(length=32), nullable=False),
    sa.Column('import_job_id', sa.String(length=32), nullable=False),
    sa.Column('source_file_name', sa.String(length=256), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_job.import_job_id'], ),
    sa.PrimaryKeyConstraint('import_file_id')
    )
    op.create_index(op.f('ix_import_file_created_at'), 'import_file', ['created_at'], unique=False)
    op.create_index(op.f('ix_import_file_import_job_id'), 'import_file', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_import_file_status'), 'import_file', ['status'], unique=False)
    op.create_table('import_item',
    sa.Column('import_item_id', sa.String(length=32), nullable=False),
    sa.Column('import_job_id', sa.String(length=32), nullable=False),
    sa.Column('source_file_name', sa.String(length=256), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('split_index', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('card_id', sa.String(length=32), nullable=True),
    sa.Column('duplicate_candidates', sa.JSON(), nullable=True),
    sa.Column('chosen_action', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['business_card.card_id'], ),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_job.import_job_id'], ),
    sa.PrimaryKeyConstraint('import_item_id')
    )
    op.create_index(op.f('ix_import_item_import_job_id'), 'import_item', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_import_item_status'), 'import_item', ['status'], unique=False)
    op.create_table('ocr_result',
    sa.Column('ocr_result_id', sa.String(length=32), nullable=False),
    sa.Column('import_item_id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('api_version', sa.String(length=64), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('field_confidence', sa.JSON(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['import_item_id'], ['import_item.import_item_id'], ),
    sa.PrimaryKeyConstraint('ocr_result_id')
    )
    op.create_index(op.f('ix_ocr_result_import_item_id'), 'ocr_result', ['import_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ocr_result_import_item_id'), table_name='ocr_result')
    op.drop_table('ocr_result')
    op.drop_index(op.f('ix_import_item_status'), table_name='import_item')
    op.drop_index(op.f('ix_import_item_import_job_id'), table_name='import_item')
    op.drop_table('import_item')
    op.drop_index(op.f('ix_import_file_status'), table_name='import_file')
    op.drop_index(op.f('ix_import_file_import_job_id'), table_name='import_file')
    op.drop_index(op.f('ix_import_file_created_at'), table_name='import_file')
    op.drop_table('import_file')
    op.drop_index(op.f('ix_card_image_import_item_id'), table_name='card_image')
    op.drop_index(op.f('ix_card_image_checksum'), table_name='card_image')
    op.drop_index(op.f('ix_card_image_card_id'), table_name='card_image')
    op.drop_table('card_image')
    op.drop_index(op.f('ix_card_contact_value_normalized'), table_name='card_contact')
    op.drop_index(op.f('ix_card_contact_card_id'), table_name='card_contact')
    op.drop_table('card_contact')
    op.drop_index(op.f('ix_login_attempt_attempted_at'), table_name='login_attempt')
    op.drop_table('login_attempt')
    op.drop_index(op.f('ix_import_job_created_at'), table_name='import_job')
    op.drop_table('import_job')
    op.drop_table('device')
    op.drop_index('ix_card_person_latest', table_name='business_card')
    op.drop_index('ix_card_exchanged_on', table_name='business_card')
    op.drop_index(op.f('ix_business_card_person_id'), table_name='business_card')
    op.drop_index(op.f('ix_business_card_is_latest'), table_name='business_card')
    op.drop_index(op.f('ix_business_card_deleted_at'), table_name='business_card')
    op.drop_index(op.f('ix_business_card_company_id'), table_name='business_card')
    op.drop_table('business_card')
    op.drop_table('user')
    op.drop_table('csv_export_log')
    op.drop_index(op.f('ix_person_full_name_normalized'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('department')
    op.drop_index(op.f('ix_company_name_normalized'), table_name='company')
    op.drop_table('company')
    op.drop_index('ix_history_target', table_name='change_history')
    op.drop_index(op.f('ix_change_history_changed_at'), table_name='change_history')
    op.drop_table('change_history')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_setting')
    op.drop_table('allowed_ip')
    # ### end Alembic commands ###
